"""Import compatible ViviMusic translations into Auralis Android resources.

Usage: python scripts/sync_vivimusic_locales.py PATH_TO_VIVI_MUSIC_CHECKOUT

ViviMusic is GPL-3.0: https://github.com/vivizzz007/vivi-music
Only translations whose English source text and format arguments match Auralis are reused.
The resulting files contain translated entries only; Android falls back to values/strings.xml
for Auralis-specific strings. Existing Auralis translations are left untouched.
"""

from __future__ import annotations

import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path
from xml.sax.saxutils import escape


ROOT = Path(__file__).resolve().parents[1]
RES = ROOT / "android/app/src/main/res"
ENGLISH = RES / "values/strings.xml"
ANDROID_NS = "http://schemas.android.com/apk/res/android"
FORMAT = re.compile(r"%(?:\d+\$)?[-#+ 0,(]*\d*(?:\.\d+)?[a-zA-Z%]")


def strings(folder: Path) -> dict[str, str]:
    result = {}
    for path in sorted(folder.glob("*.xml")):
        try:
            root = ET.parse(path).getroot()
        except ET.ParseError:
            continue
        for element in root:
            if element.tag != "string" or len(element) or "name" not in element.attrib:
                continue
            if element.attrib.get("translatable") == "false":
                continue
            result[element.attrib["name"]] = element.text or ""
    return result


def normalized(value: str) -> str:
    return re.sub(r"\s+", " ", value.replace("\\'", "'").strip())


def format_signature(value: str) -> list[str]:
    return sorted(match.group() for match in FORMAT.finditer(value) if match.group() != "%%")


def qualifier_to_tag(qualifier: str) -> str | None:
    if qualifier in {"night", "night-v31", "v31", "wae"}:
        return None
    if qualifier.startswith("b+"):
        return qualifier[2:].replace("+", "-")
    language, _, region = qualifier.partition("-r")
    language = {"in": "id", "iw": "he"}.get(language, language)
    return f"{language}-{region}" if region else language


def write_translations(source: Path) -> list[str]:
    auralis = strings(ENGLISH.parent)
    vivi_english = strings(source / "values")
    by_english: dict[str, list[str]] = {}
    for key, value in vivi_english.items():
        by_english.setdefault(normalized(value), []).append(key)

    tags = []
    for folder in sorted(source.glob("values-*")):
        qualifier = folder.name.removeprefix("values-")
        tag = qualifier_to_tag(qualifier)
        if tag is None:
            continue
        destination = RES / folder.name / "strings.xml"
        if destination.exists() and "Compatible translations adapted from ViviMusic" not in destination.read_text(encoding="utf-8")[:300]:
            tags.append(tag)
            continue
        translated = strings(folder)
        entries = []
        for auralis_key, english in auralis.items():
            candidates = by_english.get(normalized(english), [])
            translated_text = next((translated[key] for key in candidates if key in translated), None)
            if translated_text is None:
                continue
            if format_signature(english) != format_signature(translated_text):
                continue
            if translated_text.startswith("@") or "\\u" in translated_text:
                continue
            value = escape(translated_text.replace("\\'", "'").replace("'", "\\'"))
            entries.append(f'    <string name="{auralis_key}">{value}</string>')
        if not entries:
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(
            '<?xml version="1.0" encoding="utf-8"?>\n'
            '<!-- Compatible translations adapted from ViviMusic (GPL-3.0). '
            'Unlisted strings fall back to Auralis English. -->\n'
            '<resources>\n' + "\n".join(entries) + "\n</resources>\n",
            encoding="utf-8",
        )
        print(f"{tag}: {len(entries)} translated strings")
        tags.append(tag)
    return sorted(set(tags))


def write_locale_config(tags: list[str]) -> None:
    locales = ["en", *tags]
    lines = ['<?xml version="1.0" encoding="utf-8"?>',
             '<!-- Generated by scripts/sync_vivimusic_locales.py from translated resources. -->',
             f'<locale-config xmlns:android="{ANDROID_NS}">']
    lines.extend(f'    <locale android:name="{tag}" />' for tag in locales)
    lines.append('</locale-config>')
    (RES / "xml/locales_config.xml").write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    source = Path(sys.argv[1]).resolve() / "app/src/main/res"
    if not source.is_dir():
        raise SystemExit(f"Missing ViviMusic resources: {source}")
    write_locale_config(write_translations(source))
